#!/bin/bash
set -e

REPO=${REPO:-rancher}
SCRIPTPATH="$(cd "$(dirname "$0")"; pwd -P)"

source $(dirname $0)/version

package (){
    mkdir -p dist/artifacts rootfs
    pushd rootfs

    if [ "$1" == "windows" ]; then
        mkdir -p rancher
        cp ../bin/$1/$2/per-host-subnet.exe rancher/per-host-subnet.exe
        cp ../startup_per-host-subnet.ps1 rancher/startup_per-host-subnet.ps1
        zip -r ../dist/artifacts/rancher-per-host-subnet.zip rancher/
        echo "Built rancher-per-host-subnet.zip"
    else
        mkdir -p usr/bin
        cp ../bin/$1/$2/per-host-subnet usr/bin/per-host-subnet
        tar cvzf ../dist/artifacts/rancher-per-host-subnet-${ARCH}-${VERSION}.tar.gz .
        echo "Built rancher-per-host-subnet-${ARCH}-${VERSION}.tar.gz"
    fi
    popd

}

source $SCRIPTPATH/version
cd $SCRIPTPATH/..
mkdir -p dist && rm -rf dist/*

for os in $(ls bin); do
  for arch in $(ls bin/$os); do
    package $os $arch
  done
done
