#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/..

mkdir -p dist/artifacts rootfs
cd rootfs

mkdir -p usr/bin

cp ../bin/per-host-subnet usr/bin/per-host-subnet

tar cvzf ../dist/artifacts/rancher-per-host-subnet-${ARCH}-${VERSION}.tar.gz .

echo "Built rancher-per-host-subnet-${ARCH}-${VERSION}.tar.gz"
